function [bandpowerAll] = util_WM_band(EEG, epochInds)

bandpowerAll = NaN(1,numel(EEG.chanlocs)); 

fft_options = struct();
fft_options.cycles = [3 0.25];
fft_options.freqrange = [4 8];
fft_options.freqscale = 'log';
fft_options.padratio = 2;
fft_options.alpha = NaN;
fft_options.powbase = NaN;

for Ei = 1:numel(EEG.chanlocs)
    [ERSP,~,~,times,freqs,erspboot,~] = newtimef(EEG.data(Ei,:,epochInds),...
        EEG.pnts,...
        [EEG.times(1) EEG.times(end)],...
        EEG.srate,...
        'cycles',fft_options.cycles,...
        'freqs',fft_options.freqrange,...
        'freqscale',fft_options.freqscale,...
        'padratio',fft_options.padratio,...
        'alpha',fft_options.alpha,...   
        'powbase',fft_options.powbase,...
        'baseline',NaN,... % no baseline, since that is only a subtraction of the freq values, we do it manually
        'plotersp','off',...
        'plotitc','off',...
        'verbose','off');
    
    bandpower = mean(mean(ERSP)); 
    bandpowerAll(Ei) = bandpower; 
end

end