function [outlierIndices, nonOutlierIndices] = util_WM_IQR(inputVector)

% This function has been generated by OpenAI ChatGPT 
% modified by Sein Jeung 
%--------------------------------------------------------------------------

% Calculate the first and third quartiles
Q1 = prctile(inputVector, 25);
Q3 = prctile(inputVector, 75);

% Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1;

% Define the lower and upper bounds for outlier removal
lowerBound = Q1 - 1.5 * IQR;
upperBound = Q3 + 1.5 * IQR;

% Find the indices of outliers and non-outliers 
outlierIndices = (inputVector < lowerBound) | (inputVector > upperBound);
 nonOutlierIndices = ~outlierIndices;


end