function [bandpowerAll] = util_WM_band(EEG, epochInds, baseERSP)

bandpowerAll    = NaN(1,numel(EEG.chanlocs)); 
tBandWindow     = [-500, 2000]; 

fft_options = struct();
fft_options.cycles = [3 0.25];
fft_options.freqrange = [4 8];
fft_options.freqscale = 'log';
fft_options.padratio = 2;
fft_options.alpha = NaN;
fft_options.powbase = NaN;

for Ei = 1:numel(EEG.chanlocs)
    [ERSP,~,~,times,freqs,erspboot,~] = newtimef(EEG.data(Ei,:,epochInds),...
        EEG.pnts,...
        [EEG.times(1) EEG.times(end)],...
        EEG.srate,...
        'cycles',fft_options.cycles,...
        'freqs',fft_options.freqrange,...
        'freqscale',fft_options.freqscale,...
        'padratio',fft_options.padratio,...
        'alpha',fft_options.alpha,...   
        'powbase',fft_options.powbase,...
        'baseline',NaN,... % manually subtract baseline task activity
        'plotersp','off',...
        'plotitc','off',...
        'verbose','off');
    [~,tStartInd]   = min(abs(times-tBandWindow(1)));
    [~,tEndInd]     = min(abs(times-tBandWindow(2)));
    bandpower = mean(mean(ERSP(:,tStartInd:tEndInd)));
    basepower = mean(mean(baseERSP{Ei}(:,tStartInd:tEndInd))); 
    bandpowerAll(Ei) = bandpower - basepower; 
end

end