function [ERSPAll, times, freqs] = util_WM_ERSP(EEG, elecInds, epochInds)

ERSPAll = {}; 

fft_options = struct();
fft_options.cycles = [3 0.25];
fft_options.freqrange = [3 20];
fft_options.freqscale = 'log';
fft_options.padratio = 2;
fft_options.alpha = NaN;
fft_options.powbase = NaN;

for Ei = elecInds
    [ERSP,~,~,times,freqs,erspboot,~] = newtimef(EEG.data(Ei,:,epochInds),...
        EEG.pnts,...
        [EEG.times(1) EEG.times(end)],...
        EEG.srate,...
        'cycles',fft_options.cycles,...
        'freqs',fft_options.freqrange,...
        'freqscale',fft_options.freqscale,...
        'padratio',fft_options.padratio,...
        'alpha',fft_options.alpha,...   
        'powbase',fft_options.powbase,...
        'baseline',NaN,... % manually subtract baseline task activity 
        'plotersp','off',...
        'plotitc','off',...
        'verbose','off');
    
    ERSPAll{end+1} = ERSP; 
end

end