function [ERSPAllMOBI, ERSPAllSTAT, times, freqs] = WM_baseline_power(Pi, elecInds)
baseMOBIEpoch =pop_loadset('filepath', ['P:\Sein_Jeung\Project_Watermaze\WM_EEG_Data\7_epoched\sub-' num2str(Pi)], 'filename', ['sub-' num2str(Pi) '_mobi_walk.set']); 
baseSTATEpoch =pop_loadset('filepath', ['P:\Sein_Jeung\Project_Watermaze\WM_EEG_Data\7_epoched\sub-' num2str(Pi)], 'filename', ['sub-' num2str(Pi) '_stat_walk.set']);

fft_options = struct();
fft_options.cycles = [3 0.25];
fft_options.freqrange = [3 20];
fft_options.freqscale = 'log';
fft_options.padratio = 2;
fft_options.alpha = NaN;
fft_options.powbase = NaN;

ERSPAllMOBI = {}; 
EEG = baseMOBIEpoch;
for Ei = elecInds
    [ERSP,~,~,times,freqs,~,~] = newtimef(EEG.data(Ei,:,:),...
        EEG.pnts,...
        [EEG.times(1) EEG.times(end)],...
        EEG.srate,...
        'cycles',fft_options.cycles,...
        'freqs',fft_options.freqrange,...
        'freqscale',fft_options.freqscale,...
        'padratio',fft_options.padratio,...
        'alpha',fft_options.alpha,...   
        'powbase',fft_options.powbase,...
        'baseline',NaN,... % activity before 0 ms is used as baseline 
        'plotersp','off',...
        'plotitc','off',...
        'verbose','off');
    
    ERSPAllMOBI{end+1} = ERSP; 
end


ERSPAllSTAT = {}; 
EEG = baseSTATEpoch;
for Ei = elecInds
    [ERSP,~,~,times,freqs,~,~] = newtimef(EEG.data(Ei,:,:),...
        EEG.pnts,...
        [EEG.times(1) EEG.times(end)],...
        EEG.srate,...
        'cycles',fft_options.cycles,...
        'freqs',fft_options.freqrange,...
        'freqscale',fft_options.freqscale,...
        'padratio',fft_options.padratio,...
        'alpha',fft_options.alpha,...   
        'powbase',fft_options.powbase,...
        'baseline',NaN,... % activity before 0 ms is used as baseline 
        'plotersp','off',...
        'plotitc','off',...
        'verbose','off');
    
    ERSPAllSTAT{end+1} = ERSP; 
end

end